[package]
name = "imgutl"
version = "0.1.0"
edition = "2021"
authors=["Tom0427"]
description="image util for rust ğŸŒ"
license="MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
